# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Site Settings
locale                   : "en-GB"
title                    : "HAKSOAT"
title_separator          : "-"
name                     : "Habeeb Shopeju"
description              : "The personal site of Habeeb Kehinde Shopeju"
url                      : "https://www.haksoat.com"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : # "mmistakes/minimal-mistakes"
teaser                   : "/assets/images/500x300.png"
logo                     : https://res.cloudinary.com/haks/image/upload/v1554853108/logohaksoat.png
masthead_title           : "The HAKSOAT"

# Social Sharing
twitter:
  username               : haksoat

# Site Author
author:
  name             : "Habeeb Shopeju"
  avatar           : https://res.cloudinary.com/haks/image/upload/w_1000,c_fill,ar_1:1,g_auto,r_max,bo_5px_solid_red,b_rgb:262c35/v1554855417/IMG_20190219_110629.jpg
  bio              : "I play too much. But I get the job done regardless."
  location         : "Lagos, Nigeria"
  email            : shopejuh@gmail.com
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:shopejuh@email.com
    - label: "Website"
      icon: "fas fa-fw fa-link"
      # url: "https://your-website.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/haksoat"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      # url: "https://facebook.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/haksoat"
    - label: "Medium"
      icon: "fab fa-fw fa-medium"
      url: "https://medium.com/@haksoat"

#Pagination
permalink: /:categories/:title/
paginate: 3 # amount of posts to show
paginate_path: /page:num/
timezone: NL

#Collections
collections:
  projects:
    output: true
    permalink: /:collection/:path/
  activities:
    output: true
    permalink: /:collection/:path/

#Footer links
footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:shopejuh@email.com
    - label: "Website"
      icon: "fas fa-fw fa-link"
      # url: "https://your-website.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/haksoat"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      # url: "https://facebook.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/haksoat"
    - label: "Medium"
      icon: "fab fa-fw fa-medium"
      url: "https://medium.com/@haksoat"

# Build settings
# _posts is not included as it is set by default
include:
  - _pages
  - _projects
  - _activities

markdown: kramdown
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "contrast"
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

#default front matter for pages
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      toc: true

  # _projects
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: true
      share: true

  # _activities
  - scope:
      path: ""
      type: activities
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
      toc: true

#SEO
google:
  search_engine_id: "011346976017231903872:svqz6t7zvgi"

# Comments
comments:
  provider: "disqus"
  disqus:
    shortname: "haksoat-github-io"


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
